### ISSUE TITLE
Error using systemctl

### ISSUE THREAD

**Issue by gjoosen** [gotthardp/lorawan-server#105] opened 2017-05-28 18:41 UTC
Hello,
I am able run the binary just fine, but when I use Systemctl I get the following error:
`lorawanctl[4049]: erlexec: HOME must be set`
Writing `echo $HOME` does print the Home directory. 
Is there something wrong with my setup?

**Comment by gotthardp** [comment] 2017-05-28 21:40
Hello. Your system is OK, this is a bug. I will fix it tomorrow.

**Comment by kazi93** [comment] 2017-05-31 18:56
@gotthardp I am receiving the same error while stopping the server. I am using the latest versing v0.4.2. Is it fixed or I am missing something. For example the now the #echo $HOME is printing /root as home directory. Does it need to be the home>> lorawan?  as per the documentation ( useradd --home-dir /var/lib/lorawan-server --create-home lorawan.

May 31 20:42:03 vps416657.ovh.net systemd[1]: Stopping LoRaWAN Server...
May 31 20:42:03 vps416657.ovh.net lorawanctl[19357]: erlexec: HOME must be set
May 31 20:42:03 vps416657.ovh.net systemd[1]: lorawan-server.service: control process exited, code=exited status=1
May 31 20:42:03 vps416657.ovh.net lorawan-daemon[17602]: Session terminated, terminating shell... ...terminated.
May 31 20:42:03 vps416657.ovh.net systemd[1]: lorawan-server.service: main process exited, code=exited, status=143/n/a
May 31 20:42:03 vps416657.ovh.net systemd[1]: Stopped LoRaWAN Server.
May 31 20:42:03 vps416657.ovh.net systemd[1]: Unit lorawan-server.service entered failed state.
root@vps416657:/var/lib/lorawan-server/log# echo $HOME
/root
root@vps416657:/var/lib/lorawan-server/log#

**Comment by gotthardp** [comment] 2017-05-31 22:49
It's not fixed yet. It's not a bug specific to this server-- The systemd ignores whatever you set; I am trying to find some standard approach how to solve this.

**Comment by Sviests** [comment] 2017-06-02 10:08
Are you sure this is a bug? I got it working perfectly following the instructions of the binary release install, just remember to make a lorawan user like so `useradd --home-dir /var/lib/lorawan-server --create-home lorawan`

**Comment by gotthardp** [comment] 2017-06-02 10:29
Its a minor issue only. But the home is not set error shoulnt be there

**Comment by gotthardp** [comment] 2017-06-02 11:10
Now its fixed. Will be included in the release 0.4.3 which is about to be released tomorrow.

**Closed by gotthardp** 2017-06-02 11:10 UTC
Labels: bug
