### ISSUE TITLE
User interface shows unconfirmed messages.

### ISSUE THREAD

**Issue by gjoosen** [gotthardp/lorawan-server#188] opened 2017-08-23 10:00 UTC
Hello,
I've added a Node in the UI, and I do receive data, but the UI shows the messages are unconfirmed. 
It seems that the packet forwarder does receive acks. I've added a screenshot of the UI as well as the packet forwarder log. Is this a configuration problem?
<img width="1180" alt="screen shot 2017-08-23 at 11 52 44" src="https://user-images.githubusercontent.com/3176196/29610225-d8d8b092-87f9-11e7-8915-b8cdb7015b74.png">
<img width="1440" alt="screen shot 2017-08-23 at 11 50 16" src="https://user-images.githubusercontent.com/3176196/29610226-d8f37e22-87f9-11e7-9612-028755857533.png">

**Comment by gotthardp** [comment] 2017-08-23 10:26
Hello. Unconfirmed means the device didn't request an ACK. You need to convince your device to send confirmed uplinks.

**Comment by gjoosen** [comment] 2017-08-23 10:29
So, in this case the server didn't send an acknowledge to the node?

**Comment by gotthardp** [comment] 2017-08-23 10:30
No it didn't. Because the node didn't request it.

**Comment by gotthardp** [comment] 2017-09-08 20:36
The user interface included a bug, so confirmed messages were shown as unconfirmed (and vice versa). Will be fixed in 0.4.11.

**Closed by gotthardp** 2017-09-08 20:36 UTC
Labels: question
