### ISSUE TITLE
Deleting a profile that is still referenced

### ISSUE THREAD

**Issue by webfrank** [gotthardp/lorawan-server#354] opened 2018-04-03 08:37 UTC
If I delete an associated profile I cannot anymore change the profile in device form. I should re-add the deleted profile (same name), change che profile in the device form and after delete the profile.
I think a profile should not be deleted if any node is associated or fix the form and permit to select a new profile on node.
I'm using latest docker versione 0.5.4

**Comment by gotthardp** [comment] 2018-04-03 08:41
Oh, yeah. This is how it works. It's the same for all references. If you delete the referenced object, you cannot change the references anymore.

**Comment by gotthardp** [comment] 2018-06-26 13:37
This is a duplicate of #324. I close this one and keep #324 until the problem is fixed.

**Closed by gotthardp** 2018-06-26 13:37 UTC
Labels: duplicate
